name = "email4cursor"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "email4cursor"
database_id = ""  # 在本地开发时需要填入您的数据库ID

# 环境变量配置
# 本地开发时会从 .dev.vars 加载
# 生产环境需要在 Cloudflare Dashboard 中配置
[vars]
EMAIL_DOMAIN = "" 